### PR TITLE
Remove references to the incubator callstack

### PR DESCRIPTION
**Pull request by arfio**
This PR is intended to resolve the issue https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/issues/12

Some classes were not moved to profiling.core so this patch is dependent on https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/51

This fixes the following projects:
- org.eclipse.tracecompass.incubator.traceevent.core
- org.eclipse.tracecompass.incubator.traceevent.core.tests
- org.eclipse.tracecompass.incubator.inandout.core
- org.eclipse.tracecompass.incubator.kernel.core
- org.eclipse.tracecompass.incubator.tracecompass.core
- org.eclipse.tracecompass.incubator.uftrace.core
- org.eclipse.tracecompass.incubator.virtual.machine.analysis.core
- org.eclipse.tracecompass.incubator.virtual.machine.analysis.core.tests
- org.eclipse.tracecompass.incubator.kernel.ui
- org.eclipse.tracecompass.incubator.tracecompass.core
- org.eclipse.tracecompass.incubator.trace.server.product
- org.eclipse.tracecompass.incubator.perf.profiling.core
- org.eclipse.tracecompass.incubator.perf.profiling.core.tests
- org.eclipse.tracecompass.incubator.otf2.core
- org.eclipse.tracecompass.incubator.scripting.core
- org.eclipse.tracecompass.incubator.scripting.ui

[Fixes] remove incubator callstack dependencies

### CODE REVIEW

**Review by bhufmann — CHANGES_REQUESTED** [review]
I noticed that the ROCM plugins still depends on the incubator callstack. Additionally, the trace server also includes the incubator.core plug-in. Both should be addressed as well. 

Could you please update that or let me know if have a different plan for those? 

Thanks
Bernd

**Comment by bhufmann** [comment]
Trace Compass baseline build is available and this PR doesn't have any compilation errors anymore. However, there are some test errors which need to be addressed as well:

https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/actions/runs/8559375092/job/23678280523?pr=18#step:5:14103

**Comment by arfio** [comment]
The ROCm plugin will be updated separately, the incubator callstack and the ROCm plugin were removed from the trace server. The incubator analysis was kept because the trace event plugin is dependent on the aspects.
The tests errors were corrected.

**Review by bhufmann — CHANGES_REQUESTED** [review]
I'm ok to handle ROCm in a separated PR.

I noticed that the feature.xml files still have the dependencies to the incubator callstack plug-ins listed. I think they should be removed as will as part of the PR.

While checking the feature.xml files. I noticed that the XML defined call stack have not been migrate to mainline (package: . `org.eclipse.tracecompass.incubator.internal.callstack.core.xml.callstack`). The plug-in `org.eclipse.tracecompass.incubator.tracecompass.core` defines a build-in xml analysis (`GroupedTasks.xml`)  and `org.eclipse.tracecompass.incubator.traceevent.core` defines another one (`GroupedTasksTraceEvent.xml`). These 2 corresponding features.xml cannot have the incubator callstack dependencies removed just yet. 

So, I suggest to handle the xml analysis in a separate PR because it needs to be migrated first to mainline Trace Compass. However, please update this PR to update all relevant feature.xml files. WDYT?

**Comment by arfio** [comment]
Good catch, I agree with you. Do you think the xml analysis should be added to org.eclipse.tracecompass.analysis.profiling.core or org.eclipse.tracecompass.tmf.analysis.xml.core ? I personally think xml would be better.

**Comment by bhufmann** [comment]
> Good catch, I agree with you. Do you think the xml analysis should be added to org.eclipse.tracecompass.analysis.profiling.core or org.eclipse.tracecompass.tmf.analysis.xml.core ? I personally think xml would be better.

I think it should be part of `org.eclipse.tracecompass.tmf.analysis.xml.core` with the rest of the xml analysis code.

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
